/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WingsRouteImport } from './routes/wings'
import { Route as VoterIdRouteImport } from './routes/voter-id'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OrganizersRouteImport } from './routes/organizers'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as BusinessNewRouteImport } from './routes/business.new'
import { Route as BusinessIdRouteImport } from './routes/business.$id'
import { Route as ApiVoterSearchRouteImport } from './routes/api/voter-search'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiPublicOrganizerRouteImport } from './routes/api/public/organizer'
import { Route as ApiPublicMembersRouteImport } from './routes/api/public/members'
import { Route as ApiPublicCategoriesRouteImport } from './routes/api/public/categories'
import { Route as ApiPublicBusinessRouteImport } from './routes/api/public/business'
import { Route as ApiPublicBusinessIdRouteImport } from './routes/api/public/business.$id'
import { Route as ApiPublicCategoriesCategorySubcategoriesRouteImport } from './routes/api/public/categories.$category.subcategories'

const WingsRoute = WingsRouteImport.update({
  id: '/wings',
  path: '/wings',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterIdRoute = VoterIdRouteImport.update({
  id: '/voter-id',
  path: '/voter-id',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersRoute = OrganizersRouteImport.update({
  id: '/organizers',
  path: '/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessNewRoute = BusinessNewRouteImport.update({
  id: '/business/new',
  path: '/business/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoterSearchRoute = ApiVoterSearchRouteImport.update({
  id: '/api/voter-search',
  path: '/api/voter-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrganizerRoute = ApiPublicOrganizerRouteImport.update({
  id: '/api/public/organizer',
  path: '/api/public/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMembersRoute = ApiPublicMembersRouteImport.update({
  id: '/api/public/members',
  path: '/api/public/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCategoriesRoute = ApiPublicCategoriesRouteImport.update({
  id: '/api/public/categories',
  path: '/api/public/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBusinessRoute = ApiPublicBusinessRouteImport.update({
  id: '/api/public/business',
  path: '/api/public/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBusinessIdRoute = ApiPublicBusinessIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicBusinessRoute,
} as any)
const ApiPublicCategoriesCategorySubcategoriesRoute =
  ApiPublicCategoriesCategorySubcategoriesRouteImport.update({
    id: '/$category/subcategories',
    path: '/$category/subcategories',
    getParentRoute: () => ApiPublicCategoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/businesses': typeof BusinessesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/loading': typeof LoadingRoute
  '/members': typeof MembersRoute
  '/membership': typeof MembershipRoute
  '/organizers': typeof OrganizersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/voter-id': typeof VoterIdRoute
  '/wings': typeof WingsRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/voter-search': typeof ApiVoterSearchRoute
  '/business/$id': typeof BusinessIdRoute
  '/business/new': typeof BusinessNewRoute
  '/business/': typeof BusinessIndexRoute
  '/api/public/business': typeof ApiPublicBusinessRouteWithChildren
  '/api/public/categories': typeof ApiPublicCategoriesRouteWithChildren
  '/api/public/members': typeof ApiPublicMembersRoute
  '/api/public/organizer': typeof ApiPublicOrganizerRoute
  '/api/public/business/$id': typeof ApiPublicBusinessIdRoute
  '/api/public/categories/$category/subcategories': typeof ApiPublicCategoriesCategorySubcategoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/businesses': typeof BusinessesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/loading': typeof LoadingRoute
  '/members': typeof MembersRoute
  '/membership': typeof MembershipRoute
  '/organizers': typeof OrganizersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/voter-id': typeof VoterIdRoute
  '/wings': typeof WingsRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/voter-search': typeof ApiVoterSearchRoute
  '/business/$id': typeof BusinessIdRoute
  '/business/new': typeof BusinessNewRoute
  '/business': typeof BusinessIndexRoute
  '/api/public/business': typeof ApiPublicBusinessRouteWithChildren
  '/api/public/categories': typeof ApiPublicCategoriesRouteWithChildren
  '/api/public/members': typeof ApiPublicMembersRoute
  '/api/public/organizer': typeof ApiPublicOrganizerRoute
  '/api/public/business/$id': typeof ApiPublicBusinessIdRoute
  '/api/public/categories/$category/subcategories': typeof ApiPublicCategoriesCategorySubcategoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/businesses': typeof BusinessesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/loading': typeof LoadingRoute
  '/members': typeof MembersRoute
  '/membership': typeof MembershipRoute
  '/organizers': typeof OrganizersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/voter-id': typeof VoterIdRoute
  '/wings': typeof WingsRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/voter-search': typeof ApiVoterSearchRoute
  '/business/$id': typeof BusinessIdRoute
  '/business/new': typeof BusinessNewRoute
  '/business/': typeof BusinessIndexRoute
  '/api/public/business': typeof ApiPublicBusinessRouteWithChildren
  '/api/public/categories': typeof ApiPublicCategoriesRouteWithChildren
  '/api/public/members': typeof ApiPublicMembersRoute
  '/api/public/organizer': typeof ApiPublicOrganizerRoute
  '/api/public/business/$id': typeof ApiPublicBusinessIdRoute
  '/api/public/categories/$category/subcategories': typeof ApiPublicCategoriesCategorySubcategoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/assistant'
    | '/businesses'
    | '/contact'
    | '/dashboard'
    | '/loading'
    | '/members'
    | '/membership'
    | '/organizers'
    | '/privacy-policy'
    | '/services'
    | '/terms-conditions'
    | '/voter-id'
    | '/wings'
    | '/api/categories'
    | '/api/voter-search'
    | '/business/$id'
    | '/business/new'
    | '/business/'
    | '/api/public/business'
    | '/api/public/categories'
    | '/api/public/members'
    | '/api/public/organizer'
    | '/api/public/business/$id'
    | '/api/public/categories/$category/subcategories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/assistant'
    | '/businesses'
    | '/contact'
    | '/dashboard'
    | '/loading'
    | '/members'
    | '/membership'
    | '/organizers'
    | '/privacy-policy'
    | '/services'
    | '/terms-conditions'
    | '/voter-id'
    | '/wings'
    | '/api/categories'
    | '/api/voter-search'
    | '/business/$id'
    | '/business/new'
    | '/business'
    | '/api/public/business'
    | '/api/public/categories'
    | '/api/public/members'
    | '/api/public/organizer'
    | '/api/public/business/$id'
    | '/api/public/categories/$category/subcategories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/assistant'
    | '/businesses'
    | '/contact'
    | '/dashboard'
    | '/loading'
    | '/members'
    | '/membership'
    | '/organizers'
    | '/privacy-policy'
    | '/services'
    | '/terms-conditions'
    | '/voter-id'
    | '/wings'
    | '/api/categories'
    | '/api/voter-search'
    | '/business/$id'
    | '/business/new'
    | '/business/'
    | '/api/public/business'
    | '/api/public/categories'
    | '/api/public/members'
    | '/api/public/organizer'
    | '/api/public/business/$id'
    | '/api/public/categories/$category/subcategories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  BusinessesRoute: typeof BusinessesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoadingRoute: typeof LoadingRoute
  MembersRoute: typeof MembersRoute
  MembershipRoute: typeof MembershipRoute
  OrganizersRoute: typeof OrganizersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  VoterIdRoute: typeof VoterIdRoute
  WingsRoute: typeof WingsRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiVoterSearchRoute: typeof ApiVoterSearchRoute
  BusinessIdRoute: typeof BusinessIdRoute
  BusinessNewRoute: typeof BusinessNewRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  ApiPublicBusinessRoute: typeof ApiPublicBusinessRouteWithChildren
  ApiPublicCategoriesRoute: typeof ApiPublicCategoriesRouteWithChildren
  ApiPublicMembersRoute: typeof ApiPublicMembersRoute
  ApiPublicOrganizerRoute: typeof ApiPublicOrganizerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wings': {
      id: '/wings'
      path: '/wings'
      fullPath: '/wings'
      preLoaderRoute: typeof WingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter-id': {
      id: '/voter-id'
      path: '/voter-id'
      fullPath: '/voter-id'
      preLoaderRoute: typeof VoterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers': {
      id: '/organizers'
      path: '/organizers'
      fullPath: '/organizers'
      preLoaderRoute: typeof OrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/new': {
      id: '/business/new'
      path: '/business/new'
      fullPath: '/business/new'
      preLoaderRoute: typeof BusinessNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voter-search': {
      id: '/api/voter-search'
      path: '/api/voter-search'
      fullPath: '/api/voter-search'
      preLoaderRoute: typeof ApiVoterSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/organizer': {
      id: '/api/public/organizer'
      path: '/api/public/organizer'
      fullPath: '/api/public/organizer'
      preLoaderRoute: typeof ApiPublicOrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/members': {
      id: '/api/public/members'
      path: '/api/public/members'
      fullPath: '/api/public/members'
      preLoaderRoute: typeof ApiPublicMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/categories': {
      id: '/api/public/categories'
      path: '/api/public/categories'
      fullPath: '/api/public/categories'
      preLoaderRoute: typeof ApiPublicCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/business': {
      id: '/api/public/business'
      path: '/api/public/business'
      fullPath: '/api/public/business'
      preLoaderRoute: typeof ApiPublicBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/business/$id': {
      id: '/api/public/business/$id'
      path: '/$id'
      fullPath: '/api/public/business/$id'
      preLoaderRoute: typeof ApiPublicBusinessIdRouteImport
      parentRoute: typeof ApiPublicBusinessRoute
    }
    '/api/public/categories/$category/subcategories': {
      id: '/api/public/categories/$category/subcategories'
      path: '/$category/subcategories'
      fullPath: '/api/public/categories/$category/subcategories'
      preLoaderRoute: typeof ApiPublicCategoriesCategorySubcategoriesRouteImport
      parentRoute: typeof ApiPublicCategoriesRoute
    }
  }
}

interface ApiPublicBusinessRouteChildren {
  ApiPublicBusinessIdRoute: typeof ApiPublicBusinessIdRoute
}

const ApiPublicBusinessRouteChildren: ApiPublicBusinessRouteChildren = {
  ApiPublicBusinessIdRoute: ApiPublicBusinessIdRoute,
}

const ApiPublicBusinessRouteWithChildren =
  ApiPublicBusinessRoute._addFileChildren(ApiPublicBusinessRouteChildren)

interface ApiPublicCategoriesRouteChildren {
  ApiPublicCategoriesCategorySubcategoriesRoute: typeof ApiPublicCategoriesCategorySubcategoriesRoute
}

const ApiPublicCategoriesRouteChildren: ApiPublicCategoriesRouteChildren = {
  ApiPublicCategoriesCategorySubcategoriesRoute:
    ApiPublicCategoriesCategorySubcategoriesRoute,
}

const ApiPublicCategoriesRouteWithChildren =
  ApiPublicCategoriesRoute._addFileChildren(ApiPublicCategoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  BusinessesRoute: BusinessesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoadingRoute: LoadingRoute,
  MembersRoute: MembersRoute,
  MembershipRoute: MembershipRoute,
  OrganizersRoute: OrganizersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  VoterIdRoute: VoterIdRoute,
  WingsRoute: WingsRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiVoterSearchRoute: ApiVoterSearchRoute,
  BusinessIdRoute: BusinessIdRoute,
  BusinessNewRoute: BusinessNewRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  ApiPublicBusinessRoute: ApiPublicBusinessRouteWithChildren,
  ApiPublicCategoriesRoute: ApiPublicCategoriesRouteWithChildren,
  ApiPublicMembersRoute: ApiPublicMembersRoute,
  ApiPublicOrganizerRoute: ApiPublicOrganizerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
