/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WingsRouteImport } from './routes/wings'
import { Route as VoterIdRouteImport } from './routes/voter-id'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVoterSearchRouteImport } from './routes/api/voter-search'

const WingsRoute = WingsRouteImport.update({
  id: '/wings',
  path: '/wings',
  getParentRoute: () => rootRouteImport,
} as any)
const VoterIdRoute = VoterIdRouteImport.update({
  id: '/voter-id',
  path: '/voter-id',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoterSearchRoute = ApiVoterSearchRouteImport.update({
  id: '/api/voter-search',
  path: '/api/voter-search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/membership': typeof MembershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/voter-id': typeof VoterIdRoute
  '/wings': typeof WingsRoute
  '/api/voter-search': typeof ApiVoterSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/membership': typeof MembershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/voter-id': typeof VoterIdRoute
  '/wings': typeof WingsRoute
  '/api/voter-search': typeof ApiVoterSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/membership': typeof MembershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/voter-id': typeof VoterIdRoute
  '/wings': typeof WingsRoute
  '/api/voter-search': typeof ApiVoterSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/assistant'
    | '/contact'
    | '/dashboard'
    | '/membership'
    | '/privacy-policy'
    | '/services'
    | '/terms-conditions'
    | '/voter-id'
    | '/wings'
    | '/api/voter-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/assistant'
    | '/contact'
    | '/dashboard'
    | '/membership'
    | '/privacy-policy'
    | '/services'
    | '/terms-conditions'
    | '/voter-id'
    | '/wings'
    | '/api/voter-search'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/assistant'
    | '/contact'
    | '/dashboard'
    | '/membership'
    | '/privacy-policy'
    | '/services'
    | '/terms-conditions'
    | '/voter-id'
    | '/wings'
    | '/api/voter-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  MembershipRoute: typeof MembershipRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  VoterIdRoute: typeof VoterIdRoute
  WingsRoute: typeof WingsRoute
  ApiVoterSearchRoute: typeof ApiVoterSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wings': {
      id: '/wings'
      path: '/wings'
      fullPath: '/wings'
      preLoaderRoute: typeof WingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voter-id': {
      id: '/voter-id'
      path: '/voter-id'
      fullPath: '/voter-id'
      preLoaderRoute: typeof VoterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voter-search': {
      id: '/api/voter-search'
      path: '/api/voter-search'
      fullPath: '/api/voter-search'
      preLoaderRoute: typeof ApiVoterSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  MembershipRoute: MembershipRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  VoterIdRoute: VoterIdRoute,
  WingsRoute: WingsRoute,
  ApiVoterSearchRoute: ApiVoterSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
